# Generated by Django 6.0.4 on 2026-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower_id', models.CharField(help_text='e.g. V102398', max_length=10, unique=True, verbose_name='Grower ID')),
                ('grower_name', models.CharField(max_length=50, verbose_name='Grower Name')),
                ('timb_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIMB Name')),
                ('master_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Master ID')),
                ('timb_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='TIMB ID')),
                ('scheme', models.CharField(choices=[('A Scheme', 'A Scheme'), ('B Scheme', 'B Scheme'), ('D Scheme', 'D Scheme'), ('R Scheme', 'R Scheme')], max_length=10, verbose_name='Scheme')),
                ('cy26_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CY26 Hectares')),
                ('stop_order_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stop Order #')),
                ('contract_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contract Status')),
                ('area_code', models.IntegerField(verbose_name='Area Code')),
                ('area', models.CharField(max_length=20, verbose_name='Area')),
                ('group_code', models.IntegerField(verbose_name='Group Code')),
                ('group_name', models.CharField(max_length=30, verbose_name='Group')),
                ('manager_code', models.IntegerField(verbose_name='Manager Code')),
                ('manager', models.CharField(max_length=30, verbose_name='Manager')),
                ('area_manager_code', models.IntegerField(verbose_name='Area Manager Code')),
                ('area_manager', models.CharField(max_length=30, verbose_name='Area Manager')),
                ('ltech_code', models.IntegerField(verbose_name='Lead Tech Code')),
                ('ltech', models.CharField(max_length=30, verbose_name='Lead Technician')),
                ('timb_stop_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='TIMB Stop Order Value')),
            ],
            options={
                'verbose_name': 'Grower',
                'verbose_name_plural': 'Growers',
                'db_table': 'grower',
                'ordering': ['grower_id'],
                'indexes': [models.Index(fields=['scheme'], name='idx_grower_scheme'), models.Index(fields=['area_code'], name='idx_grower_area'), models.Index(fields=['group_code'], name='idx_grower_group'), models.Index(fields=['manager_code'], name='idx_grower_manager'), models.Index(fields=['area_manager_code'], name='idx_grower_area_manager')],
            },
        ),
    ]
