# Generated by Django 6.0.4 on 2026-04-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_grower'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='biometrics',
            field=models.CharField(blank=True, choices=[('Enrolled', 'Enrolled'), ('Not Enrolled', 'Not Enrolled')], max_length=20, null=True, verbose_name='Biometrics'),
        ),
        migrations.AlterField(
            model_name='grower',
            name='ltech',
            field=models.CharField(max_length=30, verbose_name='Leaf Technician'),
        ),
        migrations.AlterField(
            model_name='grower',
            name='ltech_code',
            field=models.IntegerField(verbose_name='Leaf Technician Code'),
        ),
    ]
