# Generated by Django 6.0.4 on 2026-04-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grower_biometrics_alter_grower_ltech_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expected', models.DateField(verbose_name='Date Expected')),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('transporter', models.CharField(choices=[('Bristan', 'Bristan'), ('Staudic', 'Staudic'), ('Other', 'Other')], max_length=50, verbose_name='Transporter')),
                ('truck_reg', models.CharField(max_length=20, verbose_name='Truck Reg')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('driver_id', models.CharField(help_text='Format: ##-#######-#-##', max_length=30, verbose_name='Driver ID')),
                ('qty_booked', models.PositiveIntegerField(verbose_name='Qty Booked')),
                ('qty_offloaded', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qty Offloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Truck Delivery',
                'verbose_name_plural': 'Truck Deliveries',
                'db_table': 'truck_delivery',
                'ordering': ['date_expected', 'area'],
                'indexes': [models.Index(fields=['date_expected'], name='idx_truck_date'), models.Index(fields=['area'], name='idx_truck_area')],
            },
        ),
    ]
