# Generated by Django 6.0.4 on 2026-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_truckdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdelivery',
            name='is_booked',
            field=models.BooleanField(default=True, verbose_name='Booked'),
        ),
    ]
