# Generated by Django 6.0.4 on 2026-04-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_truckdelivery_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Floor Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'db_table': 'floor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RejectionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rejection Classification',
                'verbose_name_plural': 'Rejection Classifications',
                'db_table': 'rejection_classification',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RejectedBale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('grower_number', models.CharField(max_length=20, verbose_name='Grower Number')),
                ('grower_name', models.CharField(blank=True, max_length=100, verbose_name='Grower Name')),
                ('ticket_number', models.CharField(max_length=30, verbose_name='Ticket Number')),
                ('lot_number', models.CharField(max_length=10, verbose_name='Lot Number')),
                ('group_number', models.CharField(max_length=10, verbose_name='Group Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_bales', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.floor', verbose_name='Floor')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.grower', verbose_name='Grower')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.rejectionclassification', verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Rejected Bale',
                'verbose_name_plural': 'Rejected Bales',
                'db_table': 'rejected_bale',
                'ordering': ['-date', 'floor'],
                'indexes': [models.Index(fields=['date'], name='idx_bale_date'), models.Index(fields=['floor'], name='idx_bale_floor')],
            },
        ),
    ]
