# Generated by Django 6.0.4 on 2026-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_floors_and_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedbale',
            name='ntrm_type',
            field=models.CharField(blank=True, choices=[('DIES', 'DIES'), ('F/MATTER', 'F/MATTER'), ('F/MATTER - GRASS', 'F/MATTER - GRASS'), ('F/MATTER - WIRE', 'F/MATTER - WIRE'), ('F/MATTER - PLASTIC', 'F/MATTER - PLASTIC'), ('HO', 'HO'), ('MDY', 'MDY'), ('PAIN', 'PAIN'), ('MXD', 'MXD'), ('NESTI', 'NESTI'), ('OIL', 'OIL'), ('STONI', 'STONI'), ('WET', 'WET'), ('N/A', 'N/A')], max_length=30, null=True, verbose_name='NTRM Type'),
        ),
    ]
