# Generated by Django 6.0.4 on 2026-04-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rejectedbale_ntrm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseFromHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30, verbose_name='Bales Ticket Number')),
                ('resolution_date', models.DateField(verbose_name='Resolution Date')),
                ('resolution', models.CharField(choices=[('Release to Grower', 'Release to Grower'), ('Delivery Note', 'Delivery Note'), ('Release Number', 'Release Number')], max_length=30, verbose_name='Resolution')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference (DN / Release No.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.floor', verbose_name='Floor')),
                ('rejected_bale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='accounts.rejectedbale', verbose_name='Rejected Bale')),
            ],
            options={
                'verbose_name': 'Release from Hold',
                'verbose_name_plural': 'Releases from Hold',
                'db_table': 'release_from_hold',
                'ordering': ['-resolution_date'],
                'indexes': [models.Index(fields=['resolution_date'], name='idx_release_date'), models.Index(fields=['floor'], name='idx_release_floor')],
            },
        ),
    ]
