# Generated by Django 6.0.4 on 2026-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_releasefromhold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasefromhold',
            name='resolution',
            field=models.CharField(choices=[('Release to Grower', 'Release to Grower'), ('ReOffer', 'ReOffer')], max_length=30, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('capturer', 'Capturer'), ('supervisor', 'Supervisor'), ('admin', 'Admin'), ('scaleman', 'Scaleman'), ('receiver', 'Receiver'), ('ntrm_classifier', 'NTRM Classifier')], max_length=20),
        ),
    ]
